version: "3"

services:

  web:
    build:
      context: web/
      dockerfile: Dockerfile.web
      args:
          env: "production"
    ports:
      - "3000:3000"
    container_name: ifs_web_node
    links:
      - db

  db:
    build:
      context: db/
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    container_name: ifs_db_psql
