version: "3"

services:

  web:
    build:
      context: web/
      dockerfile: Dockerfile.web
      args:
          env: "development"
    ports:
      - "3000:3000"
    volumes:
      - ./web/bin:/app/bin
      - ./web/src:/app/src
      - ./web/.env:/app/.env
    container_name: ifs_web_node
    links:
      - db

  db:
    build:
      context: db/
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    container_name: ifs_db_psql
