version: "3"

services:

  web:
    build:
      context: web/
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    volumes:
      - ./web/bin:/app/bin
      - ./web/public:/app/public
      - ./web/routes:/app/routes
      - ./web/views:/app/views
      - ./web/app.ts:/app/app.ts
      - ./web/tsconfig.json:/app/tsconfig.json

  db:
    build:
      context: db/
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
